### PR TITLE
Feature/setup webpack

### PR DESCRIPTION
**Pull request by hyzhak**
- setup webpack
- update example
- make d3 external

issue: #12

### CODE REVIEW

**Comment by vbanos** [comment]
Why do we need jQuery at all?
In a previous PR we dropped it entirely.
We just have a `RadialTree` function that we use on a page element. No jQuery plugin anymore.

**Comment by hyzhak** [comment]
@vbanos I don't need it, but it is present in `master` branch

**Comment by hyzhak** [comment]
@vbanos  btw could you check whether this build works for you? I've merged it to `master` branch in my repository https://github.com/hyzhak/wayback-radial-tree.

**Comment by vbanos** [comment]
Oh I forgot to remove it from there when we dropped jQuery support. My bad.
Since you also don't need it, please remove it from everywhere.

Note that I removed jQuery after we discussed that we should remove it from everywhere in `wayback-search-js`.

**Comment by vbanos** [comment]
@hyzhak I've tested making the build ``npm run build`` and using the example page. It works fine.
I also tested this branch with ``wayback-search-js`` and the problem I had is resolved.
I see that you load the sass file inside the src JS so it is not necessary any more to import the CSS inside the ``src/sitemap/index.js`` which created the problem.
Everything seems good.

**Comment by vbanos** [comment]
One very minor comment: I used option: ``baseURL: ""`` in ``examples/iskme-radial-tree.html`` to make it work with my server. Maybe its a more sensible default?

**Comment by hyzhak** [comment]
@vbanos I've excluded css from built js. 🤔 https://github.com/internetarchive/wayback-radial-tree/pull/14/files#diff-1a40e6c8e8713d4af22007160e07a446R43

**Pull request merged**
